---
- hosts: manager
  become: true
  any_errors_fatal: true

  tasks:
    - name: Create project directory
      file: path=/opt/{{ PROJECT }} state=directory
      tags: docker-swarm-deploy

    - name: Copy Docker Stack File
      copy:
        src: ../docker/profile-service-compose.yml
        dest: /opt/{{ PROJECT }}/profile-service-compose.yml
        owner: "root"
        group: "root"
        mode: u=rw,g=r,o=r
      tags: docker-swarm-deploy

    #- name: Replace Placeholders Version
    #  shell: >
    #    sed -i -e 's/IMAGEVERSION/{{ VERSION }}/g' docker-swarm.yml
    #  args:
    #    chdir: "/opt/{{ PROJECT }}/"
    #  become: true
    #  become_user: root
    #  tags: docker-swarm-deploy

    - name: Login to registry
      shell: >
        docker login -u {{ DOCKER_USER }} -p {{ DOCKER_PASSWORD }}
      become: true
      become_user: root
      tags: docker-swarm-deploy

    - name: Deploy Docker Stack
      shell: >
        docker stack deploy -c /opt/{{ PROJECT }}/profile-service-compose.yml profile-service --with-registry-auth
      become: true
      become_user: root
      tags: docker-swarm-deploy
